use anchor_lang::prelude::AccountMeta;
use anchor_lang::{InstructionData, ToAccountMetas};
use anchor_spl::associated_token::get_associated_token_address_with_program_id;
use derive_more::{Deref, DerefMut};
use eco_svm_std::{Bytes32, CHAIN_ID};
use intent_chainer::state::{escrow_authority_pda, vault_pda, withdrawn_marker_pda};
use intent_chainer::types::{Amount, Item, Order, Template, TemplateProgram, WAD};
use portal::types::{Call, Calldata, CalldataWithAccounts, Reward, Route, TokenAmount};
use solana_compute_budget_interface::ComputeBudgetInstruction;
use solana_sdk::instruction::Instruction;
use solana_sdk::message::Message;
use solana_sdk::pubkey::Pubkey;
use solana_sdk::signer::Signer;
use solana_sdk::transaction::Transaction;

use crate::common::{Context, TransactionResult};

/// The SPL `transfer_checked` instruction discriminator.
const TRANSFER_CHECKED_DISCRIMINATOR: u8 = 12;

/// Sentinel the SDK-side segment cutter splits on.
///
/// The production SDK encodes the route with this in every runtime position and
/// splits the blob on it, rather than computing write offsets — which is the
/// whole point of the segments representation, and is why the cutter here works
/// the same way. A hand-computed offset table would make the test agree with the
/// program by construction while both disagreed with reality.
const SENTINEL: u64 = 0xDEAD_BEEF_DEAD_BEEF;

#[derive(Deref, DerefMut)]
pub struct IntentChainer<'a>(&'a mut Context);

impl Context {
    pub fn intent_chainer(&mut self) -> IntentChainer<'_> {
        IntentChainer(self)
    }
}

/// A chained pair ready to drive: intent2's committed order plus the addresses it
/// resolves to for one particular measured amount.
pub struct ChainedIntent {
    pub order: Order,
    pub order_commitment: Bytes32,
    pub escrow_authority: Pubkey,
    pub escrow_ata: Pubkey,
    /// Intent2's typed route for the amount this was resolved at. Only meaningful
    /// for a Solana destination, where the route bytes *are* Borsh.
    pub route: Route,
    pub reward: Reward,
    pub intent_hash: Bytes32,
    pub vault: Pubkey,
    pub vault_ata: Pubkey,
    pub amount_out: u128,
}

impl IntentChainer<'_> {
    /// Builds a same-chain (SVM → SVM) order whose route is a Borsh
    /// [`portal::types::Route`] carrying the destination amount **twice** — once
    /// as the token leg and once inside an SPL `transfer_checked` call — which is
    /// the shape `DepositAddress_USDCTransfer_Solana` emits and the shape the
    /// segments mechanism exists to handle.
    ///
    /// `recipient_ata` receives the tokens on the destination side.
    pub fn svm_order(
        &mut self,
        base_mint: Pubkey,
        recipient_ata: Pubkey,
        prover: Pubkey,
        scale: u128,
        min_amount_in: u64,
    ) -> Order {
        let creator = self.creator.pubkey();
        let deadline = self.now() + 3600;
        let token_program = self.token_program;
        let (segments, items) = self.cut_svm_route(base_mint, recipient_ata, token_program);

        Order {
            portal: portal::ID,
            base_mint,
            destination: CHAIN_ID,
            template: TemplateProgram {
                vaults: vec![],
                route: Template { segments, items },
            },
            reward: Reward {
                deadline,
                creator,
                prover,
                native_amount: 0,
                // Authored at zero: the program requires it, which is what makes
                // the commitment preimage canonical.
                tokens: vec![TokenAmount {
                    token: base_mint,
                    amount: 0,
                }],
            },
            scale,
            min_amount_in,
            require_publish: false,
        }
    }

    /// Encodes intent2's route with [`SENTINEL`] in both amount positions and
    /// splits on it, exactly as the SDK does.
    ///
    /// Splitting on a sentinel rather than computing offsets is the point: it is
    /// what stops the segment table being generated by the same arithmetic the
    /// segments representation exists to replace.
    fn cut_svm_route(
        &mut self,
        base_mint: Pubkey,
        recipient_ata: Pubkey,
        token_program: Pubkey,
    ) -> (Vec<Vec<u8>>, Vec<Item>) {
        let route = self.svm_route(base_mint, recipient_ata, token_program, SENTINEL);
        let blob = borsh::to_vec(&route).unwrap();
        let needle = SENTINEL.to_le_bytes();

        let mut segments = Vec::new();
        let mut cursor = 0;
        while let Some(found) = blob[cursor..]
            .windows(needle.len())
            .position(|window| window == needle)
        {
            let at = cursor + found;
            segments.push(blob[cursor..at].to_vec());
            cursor = at + needle.len();
        }
        segments.push(blob[cursor..].to_vec());

        assert!(
            segments.len() > 1,
            "the sentinel must appear in the encoded route"
        );
        let items = (0..segments.len() - 1)
            .map(|_| Item::Amount(Amount::output(8, true)))
            .collect();

        (segments, items)
    }

    /// Intent2's route for a concrete amount — the reference the segments must
    /// reproduce byte for byte.
    pub fn svm_route(
        &mut self,
        base_mint: Pubkey,
        recipient_ata: Pubkey,
        token_program: Pubkey,
        amount: u64,
    ) -> Route {
        let executor_ata = get_associated_token_address_with_program_id(
            &portal::state::executor_pda().0,
            &base_mint,
            &token_program,
        );

        let mut data = vec![TRANSFER_CHECKED_DISCRIMINATOR];
        data.extend_from_slice(&amount.to_le_bytes());
        data.push(6); // decimals, matching `set_mint_account`

        let calldata = Calldata {
            data,
            account_count: 4,
        };
        let accounts = vec![
            AccountMeta::new(executor_ata, false),
            AccountMeta::new_readonly(base_mint, false),
            AccountMeta::new(recipient_ata, false),
            AccountMeta::new_readonly(portal::state::executor_pda().0, false),
        ];

        Route {
            deadline: self.now() + 1800,
            salt: [7u8; 32].into(),
            portal: portal::ID.to_bytes().into(),
            native_amount: 0,
            tokens: vec![TokenAmount {
                token: base_mint,
                amount,
            }],
            calls: vec![Call {
                target: token_program.to_bytes().into(),
                data: borsh::to_vec(&CalldataWithAccounts::new(calldata, accounts).unwrap())
                    .unwrap(),
            }],
        }
    }

    /// Resolves an order against a measured amount the same way the program will,
    /// producing every address the `chain` transaction has to name up front.
    ///
    /// This models exactly what an off-chain caller must do: read the escrow
    /// balance, derive intent2's vault from it, and submit. If the balance moves
    /// between the read and the transaction, the program rejects the mismatch.
    pub fn resolve(
        &mut self,
        order: &Order,
        amount_in: u64,
        recipient_ata: Pubkey,
    ) -> ChainedIntent {
        let token_program = self.token_program;
        let order_commitment = order.hash();
        let (escrow_authority, _) = escrow_authority_pda(&order_commitment);
        let escrow_ata = get_associated_token_address_with_program_id(
            &escrow_authority,
            &order.base_mint,
            &token_program,
        );

        let amount_out =
            intent_chainer::types::scale_amount(amount_in as u128, order.scale).unwrap();
        let route_bytes = order.build_route(amount_in).unwrap();
        let route: Route = borsh::from_slice(&route_bytes).expect("SVM route must deserialize");
        let _ = recipient_ata;

        let mut reward = order.reward.clone();
        reward.tokens[0].amount = amount_in;

        let route_hash = keccak(&route_bytes);
        let intent_hash =
            portal::types::intent_hash(order.destination, &route_hash, &reward.hash());
        let (vault, _) = vault_pda(&order.portal, &intent_hash);
        let vault_ata =
            get_associated_token_address_with_program_id(&vault, &order.base_mint, &token_program);

        ChainedIntent {
            order: order.clone(),
            order_commitment,
            escrow_authority,
            escrow_ata,
            route,
            reward,
            intent_hash,
            vault,
            vault_ata,
            amount_out,
        }
    }

    /// Drives `announce_order` bundled with `extra` instructions in one
    /// transaction — the configuration the handler docs recommend, where the
    /// announcement rides alongside intent1's own `portal::publish` and the two
    /// events compete for the same per-transaction log budget.
    pub fn announce_order_bundled(
        &mut self,
        order: &Order,
        extra: Vec<Instruction>,
    ) -> TransactionResult {
        let args = intent_chainer::instructions::AnnounceOrderArgs {
            order: order.clone(),
        };
        let announce = Instruction {
            program_id: intent_chainer::ID,
            accounts: intent_chainer::accounts::AnnounceOrder {
                event_authority: Pubkey::find_program_address(
                    &[b"__event_authority"],
                    &intent_chainer::ID,
                )
                .0,
                program: intent_chainer::ID,
            }
            .to_account_metas(None),
            data: intent_chainer::instruction::AnnounceOrder { args }.data(),
        };

        let payer = self.payer.insecure_clone();
        let (announce, _) = self.stage_template_instruction(announce);
        let instructions: Vec<_> = std::iter::once(
            ComputeBudgetInstruction::set_compute_unit_limit(self.compute_limit),
        )
        .chain(extra)
        .chain(std::iter::once(announce))
        .collect();
        let transaction = Transaction::new(
            &[&payer],
            Message::new(&instructions, Some(&payer.pubkey())),
            self.latest_blockhash(),
        );

        assert!(
            super::template_transport::transaction_size(&transaction)
                <= super::template_transport::PACKET_BYTES
        );
        self.send_transaction(transaction)
    }

    /// Builds a `portal::publish` instruction, to stand in for intent1's own
    /// publish when testing what shares a transaction with an announcement.
    pub fn portal_publish_instruction(
        &mut self,
        destination: u64,
        route: Vec<u8>,
        reward: Reward,
    ) -> Instruction {
        Instruction {
            program_id: portal::ID,
            accounts: portal::accounts::Publish {}.to_account_metas(None),
            data: portal::instruction::Publish {
                args: portal::instructions::PublishArgs {
                    destination,
                    route,
                    reward,
                },
            }
            .data(),
        }
    }

    /// Drives `intent_chainer::announce_order`.
    pub fn announce_order(&mut self, order: &Order) -> TransactionResult {
        let args = intent_chainer::instructions::AnnounceOrderArgs {
            order: order.clone(),
        };
        let instruction = Instruction {
            program_id: intent_chainer::ID,
            accounts: intent_chainer::accounts::AnnounceOrder {
                event_authority: Pubkey::find_program_address(
                    &[b"__event_authority"],
                    &intent_chainer::ID,
                )
                .0,
                program: intent_chainer::ID,
            }
            .to_account_metas(None),
            data: intent_chainer::instruction::AnnounceOrder { args }.data(),
        };

        self.send_template_instruction(instruction)
    }

    /// Re-derives the escrow addresses from `chained.order`.
    ///
    /// For tests that swap in an order [`Self::resolve`] cannot process — one
    /// whose route is over-length, or whose scale overflows a slot — the
    /// destination addresses are irrelevant (the call fails before reaching them)
    /// but custody must still follow the order's own commitment, or the test would
    /// fail on `InvalidEscrowAuthority` instead of the check it is pinning.
    pub fn rebind_escrow(&mut self, chained: &mut ChainedIntent) {
        let commitment = chained.order.hash();
        let (authority, _) = escrow_authority_pda(&commitment);

        chained.order_commitment = commitment;
        chained.escrow_authority = authority;
        chained.escrow_ata = get_associated_token_address_with_program_id(
            &authority,
            &chained.order.base_mint,
            &self.token_program,
        );
    }

    /// Creates the escrow ATA and mints `amount` into it, standing in for
    /// intent1's swap output landing there.
    pub fn seed_escrow(&mut self, chained: &ChainedIntent, amount: u64) {
        let mint = chained.order.base_mint;
        let authority = chained.escrow_authority;

        self.airdrop_token_ata(&mint, &authority, amount);
    }

    /// Drives `chain` with an explicit compute-unit limit, for measuring how the
    /// in-program keccak over the route scales with route length.
    pub fn chain_with_compute_limit(
        &mut self,
        chained: &ChainedIntent,
        publish: bool,
        compute_limit: u32,
    ) -> TransactionResult {
        let previous_limit = std::mem::replace(&mut self.compute_limit, compute_limit);
        let result = self.chain(chained, publish);
        self.compute_limit = previous_limit;

        result
    }

    /// Drives `chain` with a substituted `portal_program`, for the test that pins
    /// the portal as a committed field rather than a caller-chosen account.
    pub fn chain_with_portal(
        &mut self,
        chained: &ChainedIntent,
        publish: bool,
        portal_program: Pubkey,
    ) -> TransactionResult {
        self.chain_full(
            chained,
            publish,
            chained.escrow_authority,
            chained.escrow_ata,
            chained.vault,
            chained.vault_ata,
            withdrawn_marker_pda(&chained.order.portal, &chained.intent_hash).0,
            chained.order.base_mint,
            portal_program,
        )
    }

    /// Drives `intent_chainer::chain`.
    pub fn chain(&mut self, chained: &ChainedIntent, publish: bool) -> TransactionResult {
        self.chain_with_accounts(
            chained,
            publish,
            chained.escrow_authority,
            chained.escrow_ata,
            chained.vault,
            chained.vault_ata,
            withdrawn_marker_pda(&chained.order.portal, &chained.intent_hash).0,
            chained.order.base_mint,
        )
    }

    /// Drives `chain` with every address the handler validates left open, so a
    /// test can substitute a single wrong account and pin which check catches it.
    #[allow(clippy::too_many_arguments)]
    pub fn chain_with_accounts(
        &mut self,
        chained: &ChainedIntent,
        publish: bool,
        escrow_authority: Pubkey,
        escrow_ata: Pubkey,
        vault: Pubkey,
        vault_ata: Pubkey,
        withdrawn_marker: Pubkey,
        base_mint: Pubkey,
    ) -> TransactionResult {
        self.chain_full(
            chained,
            publish,
            escrow_authority,
            escrow_ata,
            vault,
            vault_ata,
            withdrawn_marker,
            base_mint,
            chained.order.portal,
        )
    }

    /// The single builder every other `chain` helper funnels through.
    #[allow(clippy::too_many_arguments)]
    fn chain_full(
        &mut self,
        chained: &ChainedIntent,
        publish: bool,
        escrow_authority: Pubkey,
        escrow_ata: Pubkey,
        vault: Pubkey,
        vault_ata: Pubkey,
        withdrawn_marker: Pubkey,
        base_mint: Pubkey,
        portal_program: Pubkey,
    ) -> TransactionResult {
        let args = intent_chainer::instructions::ChainArgs {
            order: chained.order.clone(),
            publish,
        };
        let accounts = intent_chainer::accounts::Chain {
            payer: self.payer.pubkey(),
            escrow_authority,
            escrow_ata,
            base_mint,
            vault,
            vault_ata,
            withdrawn_marker,
            portal_program,
            token_program: anchor_spl::token::ID,
            token_2022_program: anchor_spl::token_2022::ID,
            associated_token_program: anchor_spl::associated_token::ID,
            system_program: anchor_lang::system_program::ID,
        };
        let instruction = Instruction {
            program_id: intent_chainer::ID,
            accounts: accounts.to_account_metas(None),
            data: intent_chainer::instruction::Chain { args }.data(),
        };

        self.send_template_instruction(instruction)
    }

    /// An order whose spliced route is a valid Borsh `Route` of exactly
    /// `target_len` bytes, with no template items.
    ///
    /// Used to drive `publish` at the route-length ceiling: the route's size is
    /// what decides whether portal's `IntentPublished` survives the runtime's
    /// per-transaction log budget, and an oversized event is **dropped silently**
    /// rather than failing the transaction.
    pub fn large_route_order(
        &mut self,
        base_mint: Pubkey,
        prover: Pubkey,
        target_len: usize,
    ) -> Order {
        let creator = self.creator.pubkey();
        let deadline = self.now() + 3600;
        let token_program = self.token_program;

        let mut route = Route {
            deadline: self.now() + 1800,
            salt: [11u8; 32].into(),
            portal: portal::ID.to_bytes().into(),
            native_amount: 0,
            tokens: vec![TokenAmount {
                token: base_mint,
                amount: 1,
            }],
            calls: vec![Call {
                target: token_program.to_bytes().into(),
                data: vec![],
            }],
        };
        let base_len = borsh::to_vec(&route).unwrap().len();
        assert!(
            target_len >= base_len,
            "target_len {target_len} is below the {base_len}-byte minimum Route"
        );
        route.calls[0].data = vec![0xAB; target_len - base_len];
        let bytes = borsh::to_vec(&route).unwrap();
        assert_eq!(bytes.len(), target_len, "route sizing must be exact");

        Order {
            portal: portal::ID,
            base_mint,
            destination: CHAIN_ID,
            template: TemplateProgram {
                vaults: vec![],
                route: Template::literal(bytes),
            },
            reward: Reward {
                deadline,
                creator,
                prover,
                native_amount: 0,
                tokens: vec![TokenAmount {
                    token: base_mint,
                    amount: 0,
                }],
            },
            scale: WAD,
            min_amount_in: 1,
            require_publish: false,
        }
    }

    /// A route call on intent1 that forwards the executor's balance of `mint`
    /// into the chainer's escrow — the stand-in for "the swap named the escrow as
    /// its recipient".
    ///
    /// Returns both encodings portal needs: the minimal `Calldata` form that
    /// `fulfill` is given, and the full `CalldataWithAccounts` form the intent
    /// hash is computed over. Portal reconstructs the second from the first plus
    /// the transaction's accounts, so a test that used one for both would fail
    /// with a bare `BorshIoError`.
    pub fn deliver_to_escrow_call(
        &mut self,
        mint: Pubkey,
        escrow_ata: Pubkey,
        amount: u64,
    ) -> (Call, Call, Vec<AccountMeta>) {
        let token_program = self.token_program;
        let executor = portal::state::executor_pda().0;
        let executor_ata =
            get_associated_token_address_with_program_id(&executor, &mint, &token_program);

        let mut data = vec![TRANSFER_CHECKED_DISCRIMINATOR];
        data.extend_from_slice(&amount.to_le_bytes());
        data.push(6);

        let accounts = vec![
            AccountMeta::new(executor_ata, false),
            AccountMeta::new_readonly(mint, false),
            AccountMeta::new(escrow_ata, false),
            AccountMeta::new_readonly(executor, false),
        ];
        let calldata = Calldata {
            data,
            account_count: 4,
        };

        let minimal = Call {
            target: token_program.to_bytes().into(),
            data: borsh::to_vec(&calldata).unwrap(),
        };
        let with_accounts = Call {
            target: token_program.to_bytes().into(),
            data: borsh::to_vec(&CalldataWithAccounts::new(calldata, accounts.clone()).unwrap())
                .unwrap(),
        };

        (minimal, with_accounts, accounts)
    }
}

pub fn keccak(bytes: &[u8]) -> Bytes32 {
    use tiny_keccak::{Hasher, Keccak};

    let mut hasher = Keccak::v256();
    let mut hash = [0u8; 32];
    hasher.update(bytes);
    hasher.finalize(&mut hash);

    hash.into()
}

/// Convenience for the common same-unit, no-spread lane.
pub const IDENTITY_SCALE: u128 = WAD;
