name: 'Setup Rust'
description: 'Install Rust toolchain and cache dependencies'
inputs:
  rust-version:
    description: 'Rust version to install'
    required: true
  components:
    description: 'Rust components to install (comma-separated)'
    required: false
    default: ''
  cache-key-suffix:
    description: 'Suffix for cache key to differentiate between jobs'
    required: false
    default: 'default'

runs:
  using: 'composite'
  steps:
    - name: Install Rust
      uses: dtolnay/rust-toolchain@master
      with:
        toolchain: ${{ inputs.rust-version }}
        components: ${{ inputs.components }}

    - name: Cache Rust dependencies
      uses: actions/cache@v4
      with:
        path: |
          ~/.cargo/bin/
          ~/.cargo/registry/index/
          ~/.cargo/registry/cache/
          ~/.cargo/git/db/
          target/
        key: ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-${{ hashFiles('**/Cargo.lock') }}
        restore-keys: |
          ${{ runner.os }}-cargo-${{ inputs.cache-key-suffix }}-
          ${{ runner.os }}-cargo-
