[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dummy-ism = "4GHxwWyKB9exhKG4fdyU2hfLgfFzhHp2WcsSKc2uNR1k"
flash-fulfiller = "7iyEV1UD7Xs2eWNKp2xsiRh3W2kbNtiZ1ANBvNvwbn2Z"
hyper-prover = "8TzcypP5wvoWCxBu4cW32PtT9ZRAN64Nv8ATY8PGXzT8"
local-prover = "84obnegjG8PZd8PyGim4PkEtWhB77qYNkxW9Ap6Nnq3i"
portal = "BhZtMCFgqQSzZgkUmq4WuAvCkk7cZnNDUMDQmkL7KwEi"
proof-helper = "6xWQzJJNGZnKKvGCM48zB8nPCLeZBGdRFKnrW4dpnvNo"

[programs.devnet]
flash-fulfiller = "7iyEV1UD7Xs2eWNKp2xsiRh3W2kbNtiZ1ANBvNvwbn2Z"
hyper-prover = "8TzcypP5wvoWCxBu4cW32PtT9ZRAN64Nv8ATY8PGXzT8"
portal = "BhZtMCFgqQSzZgkUmq4WuAvCkk7cZnNDUMDQmkL7KwEi"
local-prover = "84obnegjG8PZd8PyGim4PkEtWhB77qYNkxW9Ap6Nnq3i"
proof-helper = "6xWQzJJNGZnKKvGCM48zB8nPCLeZBGdRFKnrW4dpnvNo"

[programs.mainnet]
flash-fulfiller = "7iyEV1UD7Xs2eWNKp2xsiRh3W2kbNtiZ1ANBvNvwbn2Z"
hyper-prover = "8TzcypP5wvoWCxBu4cW32PtT9ZRAN64Nv8ATY8PGXzT8"
portal = "BhZtMCFgqQSzZgkUmq4WuAvCkk7cZnNDUMDQmkL7KwEi"
local-prover = "84obnegjG8PZd8PyGim4PkEtWhB77qYNkxW9Ap6Nnq3i"
proof-helper = "6xWQzJJNGZnKKvGCM48zB8nPCLeZBGdRFKnrW4dpnvNo"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-localnet = "anchor build"
build-devnet = "anchor build --program-name portal && anchor build --program-name hyper-prover && anchor build --program-name local-prover && anchor build --program-name flash-fulfiller && anchor build --program-name proof-helper"
build-mainnet = "anchor build --program-name portal -- --features mainnet && anchor build --program-name hyper-prover -- --features mainnet && anchor build --program-name local-prover -- --features mainnet && anchor build --program-name flash-fulfiller -- --features mainnet && anchor build --program-name proof-helper -- --features mainnet"
deploy-devnet = "anchor deploy --provider.cluster devnet --program-name portal && anchor deploy --provider.cluster devnet --program-name hyper-prover && anchor deploy --provider.cluster devnet --program-name local-prover && anchor deploy --provider.cluster devnet --program-name flash-fulfiller && anchor deploy --provider.cluster devnet --program-name proof-helper"
deploy-mainnet = "anchor deploy --provider.cluster mainnet --program-name portal && anchor deploy --provider.cluster mainnet --program-name hyper-prover && anchor deploy --provider.cluster mainnet --program-name local-prover && anchor deploy --provider.cluster mainnet --program-name flash-fulfiller && anchor deploy --provider.cluster mainnet --program-name proof-helper"
test = "cargo test --no-fail-fast"
