[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dummy-ism = "4GHxwWyKB9exhKG4fdyU2hfLgfFzhHp2WcsSKc2uNR1k"
flash-fulfiller = "EcoFXc9egMWmADWMHqDcJgMc13iytrdjfZmGtyn7Zxig"
hyper-prover = "EcoHDiDaKXryeHsvRwoJNPEeS56uhmPDd9ksuPyF68ky"
local-prover = "EcoLAP7GStetXHQa3R1UcKb2iBbodpwcSajQkiJKgF2U"
portal = "EcooiHrTiMnfUBMw297gvPwX55HD8SCxA61tBBLV3yaV"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[programs.devnet]
flash-fulfiller = "EcoFXc9egMWmADWMHqDcJgMc13iytrdjfZmGtyn7Zxig"
hyper-prover = "EcoHDiDaKXryeHsvRwoJNPEeS56uhmPDd9ksuPyF68ky"
portal = "EcooiHrTiMnfUBMw297gvPwX55HD8SCxA61tBBLV3yaV"
local-prover = "EcoLAP7GStetXHQa3R1UcKb2iBbodpwcSajQkiJKgF2U"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[programs.mainnet]
flash-fulfiller = "EcoFXc9egMWmADWMHqDcJgMc13iytrdjfZmGtyn7Zxig"
hyper-prover = "EcoHDiDaKXryeHsvRwoJNPEeS56uhmPDd9ksuPyF68ky"
portal = "EcooiHrTiMnfUBMw297gvPwX55HD8SCxA61tBBLV3yaV"
local-prover = "EcoLAP7GStetXHQa3R1UcKb2iBbodpwcSajQkiJKgF2U"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-localnet = "anchor build"
build-devnet = "anchor build --program-name portal && anchor build --program-name hyper-prover && anchor build --program-name local-prover && anchor build --program-name flash-fulfiller && anchor build --program-name proof-helper"
build-mainnet = "anchor build --program-name portal -- --features mainnet && anchor build --program-name hyper-prover -- --features mainnet && anchor build --program-name local-prover -- --features mainnet && anchor build --program-name flash-fulfiller -- --features mainnet && anchor build --program-name proof-helper -- --features mainnet"
deploy-devnet = "anchor deploy --provider.cluster devnet --program-name portal && anchor deploy --provider.cluster devnet --program-name hyper-prover && anchor deploy --provider.cluster devnet --program-name local-prover && anchor deploy --provider.cluster devnet --program-name flash-fulfiller && anchor deploy --provider.cluster devnet --program-name proof-helper"
deploy-mainnet = "anchor deploy --provider.cluster mainnet --program-name portal && anchor deploy --provider.cluster mainnet --program-name hyper-prover && anchor deploy --provider.cluster mainnet --program-name local-prover && anchor deploy --provider.cluster mainnet --program-name flash-fulfiller && anchor deploy --provider.cluster mainnet --program-name proof-helper"
test = "cargo test --no-fail-fast"
