[toolchain]
anchor_version = "0.31.1"

[features]
resolution = true
skip-lint = false

[programs.localnet]
dummy-ism = "4GHxwWyKB9exhKG4fdyU2hfLgfFzhHp2WcsSKc2uNR1k"
flash-fulfiller = "EcoomzsaoaceYwxUSkiNqDYRyP5djqCY3AFExxKyX5rx"
hyper-prover = "EcooVeaWfmakN2sDgPFRPZpShjtLSAKd7JNHmFAq6Jyq"
local-prover = "Ecoog459avhoPbVoNnh8616uSHixCQdPPtedqNXohLLK"
portal = "EcooM1j9JpiW6dKyHQXKQxSE6RA9J9Kob89ByYW4pg3j"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[programs.devnet]
flash-fulfiller = "EcoomzsaoaceYwxUSkiNqDYRyP5djqCY3AFExxKyX5rx"
hyper-prover = "EcooVeaWfmakN2sDgPFRPZpShjtLSAKd7JNHmFAq6Jyq"
portal = "EcooM1j9JpiW6dKyHQXKQxSE6RA9J9Kob89ByYW4pg3j"
local-prover = "Ecoog459avhoPbVoNnh8616uSHixCQdPPtedqNXohLLK"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[programs.mainnet]
flash-fulfiller = "EcoomzsaoaceYwxUSkiNqDYRyP5djqCY3AFExxKyX5rx"
hyper-prover = "EcooVeaWfmakN2sDgPFRPZpShjtLSAKd7JNHmFAq6Jyq"
portal = "EcooM1j9JpiW6dKyHQXKQxSE6RA9J9Kob89ByYW4pg3j"
local-prover = "Ecoog459avhoPbVoNnh8616uSHixCQdPPtedqNXohLLK"
proof-helper = "EcoouNeez8PvCP9NJTywGdjYFAXnZ6pkMapZwymxg2GC"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
build-localnet = "anchor build"
build-devnet = "anchor build --program-name portal && anchor build --program-name hyper-prover && anchor build --program-name local-prover && anchor build --program-name flash-fulfiller && anchor build --program-name proof-helper"
build-mainnet = "anchor build --program-name portal -- --features mainnet && anchor build --program-name hyper-prover -- --features mainnet && anchor build --program-name local-prover -- --features mainnet && anchor build --program-name flash-fulfiller -- --features mainnet && anchor build --program-name proof-helper -- --features mainnet"
deploy-devnet = "anchor deploy --provider.cluster devnet --program-name portal && anchor deploy --provider.cluster devnet --program-name hyper-prover && anchor deploy --provider.cluster devnet --program-name local-prover && anchor deploy --provider.cluster devnet --program-name flash-fulfiller && anchor deploy --provider.cluster devnet --program-name proof-helper"
deploy-mainnet = "anchor deploy --provider.cluster mainnet --program-name portal && anchor deploy --provider.cluster mainnet --program-name hyper-prover && anchor deploy --provider.cluster mainnet --program-name local-prover && anchor deploy --provider.cluster mainnet --program-name flash-fulfiller && anchor deploy --provider.cluster mainnet --program-name proof-helper"
test = "cargo test --no-fail-fast"
