[package]
name = "eco-svm-std"
version = "0.1.0"
edition = "2021"

[features]
mainnet = []

[dependencies]
anchor-lang = { workspace = true }
derive-new = { workspace = true }
derive_more = { version = "2.0.1", features = ["deref"] }

[dev-dependencies]
goldie = { workspace = true }
