use anchor_lang::prelude::*;

#[error_code]
pub enum EcoRoutesError {
    NotInFundingPhase,
    TooManyTokens,
    DuplicateTokens,
    TooManyCalls,
    CallDataTooLarge,
    InvalidDeadline,
    InvalidMint,
    AlreadyFunded,
    InvalidTokenIndex,
    InvalidRefundee,
    NotFunded,
    IntentNotExpired,
    IntentStillFunded,
    InvalidHandlePayload,
    InvalidSender,
    InvalidOrigin,
    InvalidAuthority,
    TooManySenders,
    IntentNotFunded,
    NotMailbox,
    NotIgp,
    InvalidProcessAuthority,
    InvalidDispatchAuthority,
    DeadlinePassed,
    InvalidClaimer,
    NotFulfilled,
    BadSignerFlag,
    BadWritableFlag,
    AlreadyFulfilled,
    InvalidFulfillCalls,
}
