use anchor_lang::prelude::*;

#[error_code]
pub enum EcoRoutesError {
    NotInFundingPhase,
    NotInRefundingPhase,
    TooManyTokens,
    DuplicateTokens,
    TooManyCalls,
    CallDataTooLarge,
    InvalidDeadline,
    InvalidToken,
    InvalidRefundee,
    NotFunded,
    IntentNotExpired,
    IntentStillFunded,
    InvalidFulfillMessage,
    InvalidSender,
    InvalidOrigin,
    NotMailbox,
    InvalidProcessAuthority,
    InvalidClaimer,
    NotClaimable,
    AlreadyFulfilled,
    InvalidIntent,
    InvalidIntentHash,
    InvalidRouteMint,
    InvalidRouteTokenAccount,
    EmptyTokens,
    EmptyCalls,
    ZeroTokenAmount,
    InvalidAccounts,
}
